name: CI - Main

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

permissions:
  contents: read

concurrency:
  group: ci-publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ci:
    uses: ./.github/workflows/_ci-reusable.yml
    with:
      write_docker_cache: true
    permissions:
      contents: read

  publish:
    name: Publish to GHCR
    needs: ci
    uses: ./.github/workflows/_publish-ghcr.yml
    permissions:
      contents: read
      packages: write
